export { AuthController as AuthController } from './auth/auth.controller'
export { CategoryController as CategoryController } from './landing/category/category.controller'
export { CompanyController as CompanyController } from './company/company.controller'
export { HeaderController as HeaderController } from './header/header.controller'
export { SystemController as SystemController } from './system/system.controller'
export { UserController as UserController } from './user/user.controller'

// Landing pages
export { AddressBookController as AddressBookController } from './landing/address/address.book.controller'
export { AccountController as AccountController } from './landing/account/account.controller'
export { FavouriteController as FavouriteController } from './landing/favourite/favourite.controller'
export { HomeController as HomeController } from './landing/home/home.controller'
export { LoginController as LoginController } from './landing/login/login.controller'
export { ProductsController as ProductsController } from './landing/products/products.controller'
export { OrderController as OrderController } from './orders/order.controller'
export { SignupController as SignupController } from './landing/signup/signup.controller'
